### PR TITLE
Move js yaml library to top

### PR DESCRIPTION
**Pull request by dknezicd**
When cache is clear in browser, it references js-yaml.js before it's loaded. This resolves this issue

### CODE REVIEW

**Review by cnovak — CHANGES_REQUESTED** [review]
`src/Plugin/Field/FieldFormatter/SmartDocsFormatter.php` looks good, but what is `js/main.js`?

**Comment by dknezicd** [comment]
> `src/Plugin/Field/FieldFormatter/SmartDocsFormatter.php` looks good, but what is `js/main.js`?

js/main.js was a modification to the smartdocs 1.1 main.js file on the timeout but it should not be part of this PR

**Review by cnovak — APPROVED** [review]
LGTM

**Comment by cnovak** [comment]
Fixes #70

**Pull request merged**
