### PR TITLE
[#38] Update the max length for the base field name

### LINKED ISSUE #38: APIDoc field "name" is too short
**Is your feature request related to a problem? Please describe.**
We have specs with a name more than 50 chars, however the BaseFieldDefinition for field name has the setting max_length 50 characters (ergo the db field length to 50 chars also).

**Describe the solution you'd like**
Change field to be 255 chars.

## Steps to reproduce
1. Enabled API Catalog module
2. Create API Doc with a name larger than 50 chars
3. The field will be truncated to 50 chars.

Source: https://community.apigee.com/questions/69668/drupal-8-apidoc-field-name-has-max-length-of-50-ch.html

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #38

### CODE REVIEW

**Review by jacine — APPROVED** [review]
Thanks so much @arshad!  

Tested this and all is well, field now allows 255 chars.

```drush updb -y
The following updates are pending:

apigee_api_catalog module : 
  8701 -   Update the length of the name field. 

Do you wish to run all pending updates? (y/n): y
Performing apigee_api_catalog_update_8701                                                                                                     [ok]
Cache rebuild complete.                                                                                                                       [ok]
Finished performing updates.    
```

**Comment by jmburnz** [comment]
Awesome @jacine, that's great news!

**Comment by jacine** [comment]
> Awesome @jacine, that's great news!

Yeah! I’ll roll a new release tomorrow morning, and update here when it’s done. 😁

**Comment by jacine** [comment]
Release has been published: https://www.drupal.org/project/apigee_api_catalog/releases/8.x-1.0-rc2

:smiley:

**Pull request merged**
